### ISSUE TITLE
SIP 1 - ISA refactored logic, inspection results and variable corrections - 10.01.2020

### ISSUE THREAD

**Issue by rav-andre** [Sintrop/SIP#1]
A partir de agora iremos trabalhar com os SDPs, ou Sintrop Development Proposal, ou proposta de desenvolvimento do software da Sintrop. O objetivo é clarear, exemplificar e registrar as instruções de desenvolvimento do período.

As tasks consideradas essenciais para a próxima apresentação foram listadas por prioridade. As demais tasks foram listadas como extras. Apesar de estarem como extras, elas são de grande valor para a próxima apresentação e quanto mais forem feitas melhor. 

Essa primeira semana do ano, pelo fato da apresentação do projeto marcada para a próxima segunda dia 10, será uma semana intensa. Alguns dos pontos o desenvolvimento já foi iniciado, outros ainda não. Segue então os principais pontos de desenvolvimento:

## Prioridade 1 - Exibição dos dados e resultado das inspeções

Já em desenvolvimento, essa task é a prioridade 1 da nossa semana. Muito pelo fato de que exibir o resultado das inspeções é fundamental para a lógica e entendimento do sistema.

O @BrennoGomez comentou que precisava de algumas coisas do back-end para terminar essa tarefa. @BrennoGomez pode comentar aqui o que você precisa do back-end??

(
@everson-ever adicionei aqui abaixo o que preciso:

Como os dados do índice da categoria já é pego o resultado nessas ultimas atualizações tanto o ISA quanto o resultado da categoria. Uma coisa que precisava era uma lista pelo menos do que significa cada resultado. Os significados de sustentável, parcialmente sustentável, neutro, etc... Exemplo:
Sustentável: Sua agricultura foi classificada como sustentável, isso significa que todas as verificações de estrutura para uma lavoura/ agricultura atendem o requisito de reaproveitamento de água, adubos e anti-pragas ecologicamente corretos e não tóxicos.

Essas coisas que precisa para por nesse resultado de inspeção.

)

O resultado que deverá aparecer é o nome da categoria, a descrição da categoria e nível de sustentabilidade que o ativista avaliou. Ele deverá aparecer nos seguintes locais:

### 1 - My Account
![image](https://user-images.githubusercontent.com/79549809/147973003-90fd3433-d0a7-4370-81dc-75250d149e2a.png)

Talvez colocar uma seta para abrir e exibir os dados, semelhante ao que está no ISA. 

### 2 - Página das inspeções.
![image](https://user-images.githubusercontent.com/79549809/147973677-85e6b7f9-6ed0-478a-bb0f-1aeaabb99b4f.png)

Mesma lógica, botão que exibe o resultado da inspeção. 

Coloquei em vermelho que quando a inspeção não tiver sido finalizado, o botão muda para um de acompanhar resultado. Futuramente desenvolveremos essa página, por enquanto só o botão mesmo.

Reforço aqui também que o resultado também deve aparecer no caso dos ativista, onde irá mostrar as inspeções que ele realizou.

## Prioridade 2 - Implementação correta do score das categorias do ISA

Esse ponto já foi discutido anteriormente e nas últimas reuniões achamos melhor deixar com o valor variando de -10 a 10. Ficando assim:

TotallyNotSustainable -10
MostlyNotSustainable -5
Neutro 0
MostlySustainable 5
TotallySustainable 10

Ou seja, o produtor irá receber uma nota de acordo com esses níveis para cada categoria do ISA.
O resultado final, ou o ISA da inspeção será a soma desses resultados. O resultado por sua vez poderá ser negativo, no caso de um resultado onde o produtor contribui negativamente com a natureza ou positivo, no caso de contribuir positivamente.

## Prioridade 3 - Correção das variáveis ISA e Score.

Atualmente as variáveis Isa e Score não estão funcionando, conforme imagem abaixo:
![image](https://user-images.githubusercontent.com/79549809/147974600-9ee812d5-fb41-4440-8453-3f9b0e466e5f.png)
O resultado deverá aparecer na página MyAccount e também nas páginas de ranking.

### Score
Substituiremos o "Score" por "ISA Score", que representa a soma total de pontos que o produtor recebeu. 

Se na primeira inspeção o ISA da inspeção do produtor foi de 20 pontos, e de 25 pontos na segunda, esse resultado deverá mostrar a soma desses valores, no exemplo 45.

### ISA
Substituiremos o "ISA" por "ISA average", ou média do ISA.

O ISA average será o ISA score dividido pela quantidade de inspeções recebidas.

Como o back-end já envia o Score e a quantidade de inspeções, esse cálculo deverá ser feito no front-end.

## Prioridade 4 - Alterações das frases

Super fácil, apenas alterar as frases e palavras. Será enviada por aqui a lista de alterações necessárias após a publicação da próxima versão.

## Extra 1 - Página estática dos resultados e QR code

O objetivo dessa tarefa é utilizar o QR code na apresentação, e pedir para que os participantes usem a câmera do seu celular em uma foto de uma embalagem que utilizou o sistema da Sintrop com o QR redirecionando para essa página.

O QR envia de forma dinâmica para a página MyAccount do produtor. Porém para acessar essas informações, seria preciso uma conexão do MetaMask na rede. Para facilitar, faremos uma página de exemplo com os dados fictícios. 

Publicação de uma página no subdomínio example.sintrop.com de uma cópia com os dados mockados simulando o resultado.

É bem importante que ela seja feita pensando na versão mobile, já que ela será majoritariamente utilizada pelo celular.

## Extra 2 - Implementações e melhoria da lógica de distribuição de desenvolvedor 

Desenvolvimento em andamento, na reunião acompanharemos a evolução para registrar aqui as informações referentes.

**Comment by rav-andre** [comment]
@everson-ever  @BrennoGomez seguem as correções necessárias:

### cadastro de categorias produtor
Quando fui cadastrar uma categoria, a aplicação não permitiu cadastrar como ativista e somente como produtor. Deve ser o contrário, com os ativistas cadastrando.

### título página ISA
Está como "Agriculture Index Sustainable". Alterar para "Sustainable Agriculture Index".

![image](https://user-images.githubusercontent.com/79549809/148611253-1341cbfd-690c-42b6-9d7f-2a71089db343.png)

### botão "create new inspection"
Esse botão deve estar escrito "Request new inspection" para fazer sentido.
![image](https://user-images.githubusercontent.com/79549809/148612076-c6077750-2b2a-4119-9c5a-b79ec64b62a6.png)

### Producer e activist ranking
![image](https://user-images.githubusercontent.com/79549809/148612726-df9fdf37-8563-484b-8cbf-aaa75c188307.png)

Nessas páginas a quantidade de inspeções recebidas e o ISA score não está aparecendo.

**Comment by rav-andre** [comment]
@everson-ever @BrennoGomez Maioria dessas tasks já foram certo?? Pra vcs atualizarem aqui para eventualmente fecharmos essa issue.

**Comment by BrennoGomez** [comment]
Sim, todas feitas.
